### ISSUE TITLE
Create a Search Page

### ISSUE THREAD

**Issue by ximui23** [Team-Sun/CS4800-Project#22]

**Comment by Andr3wD** [comment]
Added. Just need linking with backend.

**Comment by Andr3wD** [comment]
Basic backend linking done by @Andr3wD. Need to flush out backend linking and add clickable refs to specific notes on page.

**Comment by Andr3wD** [comment]
Waiting for Jon to merge master_temp with his completed search page.

**Comment by Andr3wD** [comment]
Done
